In [1]:
import numpy as np
import pandas as pd

In [28]:
# calculate type 1 error
def er1(y, y_pred):
    return np.mean(1.0 * np.abs(y_pred - y))

# calculate type 2 errr
def er2(y, y_pred):
    return np.mean(np.abs(y_pred - y) / y)

In [29]:
x = np.array(pd.read_csv('t1_val.csv', header=None))

In [30]:
Y = np.load('../../Y_train.npz')['arr_0']

In [31]:
er1(Y[:, 0], x[:, 0]) * 300 + er1(Y[:, 1], x[:, 1]) + er1(Y[:, 2], x[:, 2]) * 200

52.26966026580412

In [32]:
er2(Y[:, 0], x[:, 0]) + er2(Y[:, 1], x[:, 1]) + er2(Y[:, 2], x[:, 2])

0.8915532850328118

In [14]:
np.set_printoptions(precision=9)
np.set_printoptions(linewidth=np.inf)
np.set_printoptions(suppress=True)

In [15]:
x

array([[  0.06740463 , 112.245735   ,   0.80511963 ],
       [  0.89134574 , 165.47267    ,   0.60224265 ],
       [  0.7790148  , 229.2128     ,   0.6060712  ],
       ...,
       [  0.12455499 , 127.15867    ,   0.7187448  ],
       [  0.82164323 , 140.8724     ,   0.54571223 ],
       [  0.020427734,  47.042175   ,   0.520169   ]])

In [16]:
Y

array([[  0.130754295, 122.285765106,   0.803669961],
       [  0.992038437, 177.303640336,   0.598635874],
       [  0.893321366, 247.923576966,   0.603514602],
       ...,
       [  0.109349751, 217.542831838,   0.719322491],
       [  0.962318662, 118.539414964,   0.544724293],
       [  0.031806108,  45.975357377,   0.517768074]])

In [19]:
sum = []
for i in range(47500):
    sum.append(np.abs(Y[i][0] - x[i][0]))

In [20]:
sum = np.array(sum)
sum

array([0.063349665, 0.100692697, 0.114306566, ..., 0.015205239, 0.140675432, 0.011378374])

In [21]:
sum.shape

(47500,)

In [22]:
np.sum(sum)

4782.79440349618